export const RETRIEVE_COURSES = "RETRIEVE_COURSES";
export const RETRIEVE_SINGLE_COURSES = "RETRIEVE_SINGLE_COURSE";
export const RETRIEVE_LESSONS = "RETRIEVE_LESSONS";
export const RETRIEVE_SINGLE_LESSONS = "RETRIEVE_SINGLE_LESSON";
export const RETRIEVE_TOPIC = "RETRIEVE_TOPIC";
export const CLEAR_TOPIC_DATA = "CLEAR_TOPIC_DATA";
export const RETRIEVE_SINGLE_TOPIC = "RETRIEVE_SINGLE_TOPIC";
export const DND_CHANGE = "DND_CHANGE";
export const BUILDER_CHANGE = "BUILDER_CHANGE";
export const BLOCK_CHANGE = "BLOCK_CHANGE";
export const CLEAR_STATE_DATA = "CLEAR_STATE_DATA";

export const POST_PER_PAGE = 12;